[phases.setup]
nixPkgs = ["python311", "nodejs_20", "pnpm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "pnpm install"
]

[phases.build]
cmds = [
    "pnpm run build",
    "mkdir -p backend/static",
    "cp -r dist/* backend/static/"
]

[start]
cmd = "python backend/main.py"

