[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm run build && mkdir -p backend/static && cp -r dist/* backend/static/"

[deploy]
startCommand = "python backend/main.py"
healthcheckPath = "/api/game/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
FLASK_ENV = "production"
PORT = "5000"
