[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm run build && cp -r dist/* backend/static/"

[deploy]
startCommand = "python backend/main.py"
# Remove the health check lines
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
FLASK_ENV = "production"
PORT = "5000"
