[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python backend/main.py"
healthcheckPath = "/api/game/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
FLASK_ENV = "production"
PORT = "5000"

